services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - '8880:8880'
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - '8881:8881'
